### ISSUE TITLE
💗 the screenshots!

### ISSUE THREAD

**Issue by PySimpleGUI** [brlnoble/DataLoggerProgram#8]
Aha!

I've got some nice context to go with your window now.

Thank you for adding screenshots to your readme.  It's very thorough.

The changes have been added to PySimpleGUI that support the operations for the Custom Titlebar.

Very attractive GUI!  Nice work.

![image](https://user-images.githubusercontent.com/46163555/184445871-2a74201c-8741-4246-9a82-aa49cb616293.png)

**Comment by brlnoble** [comment]
Thank you so much!

This has been a project I started back in January and I'm trying to get done within the next two weeks before I finish my internship.

I really appreciate your dedication to PySimpleGUI and all the support you've given me!

**Comment by PySimpleGUI** [comment]
> This has been a project I started back in January

WOW!  That's a lot of time and energy you've put into this project.  No wonder it looks so great!

The readme, with your extensive checklists, and images really add polish.... and not just images, but video screen captures using GIFs.  Very impressive work Brandon.

Wait... you're a student???  (sorry, just now looked at your GitHub home).

Your employer is very fortunate to have you working on this project.  You did BOTH the hardware and the software?  Really impressive stuff.  You've found your gift, your calling, your purpose.  Congratulations!
